gcc -g racerX_server.c -o racerX_server \
      -I"C:\OpenCV\cxcore\include" \
      -I"C:\OpenCV\cv\include" \
      -I"C:\OpenCV\otherlibs\highgui" \
      -L"C:\OpenCV\lib" -lcxcore -lcv -lhighgui -lpthread

